### PR TITLE
Fix offset warning shown when using invalid version for breakpoint

### LINKED ISSUE #1570: Attempting to --set/--unset a breakpoint on a specific migration that has not been run generates warnings.
Missing a check to make sure that the target migration is in the `up` state.

```
 [snip]
   up  20190708115702  2019-07-08 10:48:31  2019-07-08 10:48:31  Ret76AddNonStockIndicatorToProductsTable
     up  20190708131101  2019-07-08 10:48:31  2019-07-08 10:48:31  Ret20ImplementLocationsForeignKey
         BREAKPOINT SET
   down  20190708135901                                            Bac2548BackfillCompanyAndUserIds
   down  20190708135902                                            Bac2548BackfillCompanyIdOnFieldData
   down  20190708135903                                            Bac2548BackfillCompanyIdOnItemInstances
   down  20190708135904                                            Bac2548BackfillCompanyIdOnSessions
   down  20190708135905                                            Ret50AddStatusToSupplier
   down  20190709114801                                            Bac2538CreateOrderItemInvoicedTable
   down  20190710100601                                            Ret36AddRetailProductsToSuppliersTable
   down  20190710100602                                            Ret55AddCreatedByAndUpdatedByToStockMovements

✘-2 2019-07-10 10:06:19 richardquadling@Richards-MacBook-Pro:~/dt/app $  [master ↑·153|✚ 6…6⚑ 2]$ pxb --set -t 20190709114801
Phinx by CakePHP - https://phinx.org. version 0.10.8

using config file ./phinx.php
using config parser php
using migration paths 
 - /Users/richardquadling/dt/app/migrations
using seed paths 
 - /Users/richardquadling/dt/app/seeds
using environment development
PHP Notice:  Undefined offset: 20190709114801 in /Users/richardquadling/dt/app/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php on line 1029

Notice: Undefined offset: 20190709114801 in /Users/richardquadling/dt/app/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php on line 1029
PHP Notice:  Undefined offset: 20190709114801 in /Users/richardquadling/dt/app/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php on line 1043

Notice: Undefined offset: 20190709114801 in /Users/richardquadling/dt/app/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php on line 1043
 Breakpoint cleared for 20190709114801 Bac2538CreateOrderItemInvoicedTable
```

### PR DESCRIPTION
**Pull request by MasterOdin**
Fixes #1570

When attempting to set or unset a breakpoint version that is invalid, an offset warning was generated. This fixes it to return a phinx comment that version is not valid instead.

### CODE REVIEW

File: src/Phinx/Db/Adapter/AdapterInterface.php [hunk 1]
```diff
@@ -153,15 +153,6 @@ public function getOutput();
...
     public function migrated(MigrationInterface $migration, $direction, $startTime, $endTime);
 
-    /**
-     * Toggle a migration breakpoint.
-     *
-     * @param \Phinx\Migration\MigrationInterface $migration
-     *
-     * @return \Phinx\Db\Adapter\AdapterInterface
-     */
-    public function toggleBreakpoint(MigrationInterface $migration);
```
Comment (dereuromark) [inline src/Phinx/Db/Adapter/AdapterInterface.php]: We are removing interface methods here on master?

Comment (MasterOdin) [reply src/Phinx/Db/Adapter/AdapterInterface.php]: reversed, going to open a PR on 0.next for this later.
