### PR TITLE
Fix SQLiteAdapter::getColumns with Literal column

### LINKED ISSUE #2330: Cannot get columns for sqlite with Literal column type
> That said, it's not clean to just assume that `getPhinxType` returns a string for key "name" and then pass that to `parseDefaultValue` in `getColumns`. This leads to a type error when "name" is a Literal. Instead, a meaningful exception should be thrown in that case that mentions the table name, column name, and given type (string). But that's another issue. 

 _Originally posted by @InvisibleSmiley in [#2319](https://github.com/cakephp/phinx/issues/2319#issuecomment-2478521804)_

### PR DESCRIPTION
**Pull request by MasterOdin**
Fixes #2330

PR fixes a bug where `SQLiteAdapter::getColumns` would throw an exception if the table had a column with a `Literal` type. This was due to a type error when passing the type of `SQLiteAdapter::parseDefaultValue` which requires the type be a string. While I could have modified `parseDefaultValue` to accept a `string|Literal`, as the function is defined as `protected`, this would have been a BC break, and so I went with converting the `$type['name']` to a string in the caller (`getColumns`) instead.

### CODE REVIEW

File: tests/Phinx/Db/Adapter/SQLiteAdapterTest.php [hunk 1]
```diff
@@ -2430,13 +2430,16 @@ public function testAlterTableForeignKeyConstraintValidationNotRunningWithDisabl
...
     {
         $createQuery = <<<'INPUT'
-CREATE TABLE `test` (`real_col` DECIMAL)
+CREATE TABLE `test` (`real_col` FOO)
 INPUT;
         $this->adapter->execute($createQuery);
         $table = new Table('test', [], $this->adapter);
         $columns = $table->getColumns();
         $this->assertCount(1, $columns);
-        $this->assertEquals(Literal::from('decimal'), array_pop($columns)->getType());
```
Comment (MasterOdin) [inline tests/Phinx/Db/Adapter/SQLiteAdapterTest.php:2439]: `DECIMAL` is an accepted type, so `->getType()` was returning `"decimal"`, but since we were doing `assertEquals`, which equates to `Literal::from('decimal') == 'decimal'`, the test was passing (as `Literal` was being converted to a string).

This is also why I added an assertion on the actual type of `getType()`.
