### PR TITLE
Fix inserting multiple rows without zero key

### LINKED ISSUE #1565: Bug: inserting multiple rows fails when keys are modified
I just encountered an issue with a migration. On inserting multiple rows of data with `$this->table('my_table')->insert($data);` the migration failed with multiple error notices: "PHP Notice:  Array to string conversion in /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php on line 306" and finally "SQLSTATE[42S22]: Column not found: 1054 Unknown column '2' in 'field list'."

Some debugging lead me to this line: https://github.com/cakephp/phinx/blob/7187e558ab70d5ac2197d197234ce6a5faf5cfbf/src/Phinx/Db/Table.php#L591. Turns out that the check to determine whether to insert multiple rows or a single row expects the key of the first item to be zero. Since I was building my array dynamically and ran it through array_map and array_filter, the first item happened to have 2 as it's key. Running my array through array_values before passing it to the insert function solves my issue, but it would be nice if this is done in the insert method (`$data = array_values($data);` would do the trick).

### PR DESCRIPTION
**Pull request by skript-cc**
Fixes #1565

### CODE REVIEW

File: src/Phinx/Db/Table.php [hunk 1]
```diff
@@ -588,7 +588,8 @@ public function addTimestampsWithTimezone($createdAt = null, $updatedAt = null)
     public function insert($data)
     {
         // handle array of array situations
-        if (isset($data[0]) && is_array($data[0])) {
+        $firstKey = array_shift(array_keys($data));
```
Comment (lorenzo) [inline src/Phinx/Db/Table.php]: You can only pass variables to `array_shift` If you pass a function call, it results in an error

Comment (skript-cc) [reply src/Phinx/Db/Table.php]: Hmm, oke. Didn't saw any errors while running the tests. Whatever, easy change.

**Comment by lorenzo** [comment]
Thanks!
