### PR TITLE
fix failing tests for mysql 8

### LINKED ISSUE #1751: Investigate mysql 8 test failures
Relevant travis build: https://travis-ci.org/github/MasterOdin/phinx/builds/672758069

Looks like using MySQL 8 causes a handful of tests to fail. Need to investigate to figure out what's going on and make sure phinx is forward facing. Should update the matrix to test both on minimally supported mysql as well as newest version, related to: https://github.com/cakephp/phinx/issues/1590.

### PR DESCRIPTION
**Pull request by MasterOdin**
Closes #1751

MySQL 8.0.17 deprecated usage of the display width for integer data types, stating that it did not really do anything as it would allow integers to go beyond the specified width, and was only really used when you wanted to pad a number. The tests have been modified now to check on version of mysql to determine what the expected type for integer columns will be, but a more proper (and breaking) fix would be to probably not bother with display widths at all for MysqlAdapter.

### CODE REVIEW

**Comment by MasterOdin** [comment]
I realize I did not mention in the message that some tests were failing as it appears that mysql 8 is now returning column's names capitalized how it is in the DB. All of the information_schema tables have fully capitalized column names. However, the query itself remains case insensitive. A dumb approach and prone to break people's expectations, but that's MySQL I guess.

File: tests/Phinx/Db/Adapter/MysqlAdapterTest.php [hunk 1]
```diff
@@ -48,6 +48,11 @@ public function tearDown(): void
         unset($this->adapter);
     }
 
+    private function usingMysql8(): bool
+    {
+        return version_compare($this->adapter->getAttribute(\PDO::ATTR_SERVER_VERSION), '8') > -1;
```
Comment (othercorey) [inline tests/Phinx/Db/Adapter/MysqlAdapterTest.php:53]:
```suggestion
        return version_compare($this->adapter->getAttribute(\PDO::ATTR_SERVER_VERSION), '8.0.0', '>=');
```

**Comment by othercorey** [comment]
This needs a mysql 8 test environment to check. We can copy the github actions setup used by cakephp/cakephp.

File: tests/Phinx/Db/Adapter/MysqlAdapterTest.php [hunk 2]
```diff
@@ -183,12 +188,12 @@ public function testCreateTableWithComment()
         $this->assertFalse($this->adapter->hasColumn('ntable', 'address'));
 
         $rows = $this->adapter->fetchAll(sprintf(
-            "SELECT table_comment FROM INFORMATION_SCHEMA.TABLES WHERE table_schema='%s' AND table_name='ntable'",
+            "SELECT TABLE_COMMENT FROM INFORMATION_SCHEMA.TABLES WHERE table_schema='%s' AND table_name='ntable'",
```
Comment (othercorey) [inline tests/Phinx/Db/Adapter/MysqlAdapterTest.php:191]: Why doesn't this update all column names?

File: tests/Phinx/Db/Adapter/MysqlAdapterTest.php [hunk 3]
```diff
@@ -542,15 +547,15 @@ public function testAddComment()
 
         $rows = $this->adapter->fetchAll(
             sprintf(
-                "SELECT table_comment
+                "SELECT TABLE_COMMENT
```
Comment (othercorey) [inline tests/Phinx/Db/Adapter/MysqlAdapterTest.php:550]: Same here.

File: tests/Phinx/Db/Adapter/MysqlAdapterTest.php [hunk 4]
```diff
@@ -564,15 +569,15 @@ public function testChangeComment()
...
```
Comment (othercorey) [inline tests/Phinx/Db/Adapter/MysqlAdapterTest.php:572]: And here.

File: tests/Phinx/Db/Adapter/MysqlAdapterTest.php [hunk 5]
```diff
@@ -586,15 +591,15 @@ public function testDropComment()
...
```
Comment (othercorey) [inline tests/Phinx/Db/Adapter/MysqlAdapterTest.php:594]: Andhere.

File: tests/Phinx/Db/Adapter/MysqlAdapterTest.php [hunk 6]
```diff
@@ -676,73 +681,39 @@ public function testAddColumnWithDefaultLiteral()
...
-    {
-        $table = new \Phinx\Db\Table('table1', [], $this->adapter);
-        $table->save();
-        $this->assertFalse($table->hasColumn('user_id'));
-        $table->addColumn('user_id', 'biginteger', ['signed' => false])
-              ->save();
-        $rows = $this->adapter->fetchAll('SHOW COLUMNS FROM table1');
-        $this->assertEquals('bigint(20) unsigned', $rows[1]['Type']);
+        $type = $sql_type;
+        if (!$this->usingMysql8()) {
```
Comment (othercorey) [inline tests/Phinx/Db/Adapter/MysqlAdapterTest.php:712]: This should probably be changed to an explicit feature/requirement support check.

File: tests/Phinx/Db/Adapter/MysqlAdapterTest.php (hunk 1 above)
Comment (MasterOdin) [reply tests/Phinx/Db/Adapter/MysqlAdapterTest.php]: Did not know about that third parameter, done.

File: tests/Phinx/Db/Adapter/MysqlAdapterTest.php (hunk 2 above)
Comment (MasterOdin) [reply tests/Phinx/Db/Adapter/MysqlAdapterTest.php]: The columns in the where clause are case insensitive, so didn't think to update them. Done now.

File: tests/Phinx/Db/Adapter/MysqlAdapterTest.php (hunk 3 above)
Comment (MasterOdin) [reply tests/Phinx/Db/Adapter/MysqlAdapterTest.php:550]: Done

File: tests/Phinx/Db/Adapter/MysqlAdapterTest.php (hunk 4 above)
Comment (MasterOdin) [reply tests/Phinx/Db/Adapter/MysqlAdapterTest.php:572]: Done

File: tests/Phinx/Db/Adapter/MysqlAdapterTest.php (hunk 5 above)
Comment (MasterOdin) [reply tests/Phinx/Db/Adapter/MysqlAdapterTest.php:594]: Done

File: tests/Phinx/Db/Adapter/MysqlAdapterTest.php (hunk 6 above)
Comment (MasterOdin) [reply tests/Phinx/Db/Adapter/MysqlAdapterTest.php:712]: Are you asking me to split this into two separate functions (one for mysql 8 and for not)? Or are you saying to block using widths for MySQL 8?

**Comment by MasterOdin** [comment]
> This needs a mysql 8 test environment to check. We can copy the github actions setup used by cakephp/cakephp.

I'd be happy to convert the current build environments from Travis and appveyor to use github actions if that's desired by cakephp folks.

**Comment by othercorey** [comment]
> I do agree, though there's currently no great way to do that and I'm not sure I'd want to incorporate into this PR and rewrite of the Travis configuration to support testing mysql 8.

Well, nothing is currently testing these changes. Just need to create a single mysql 8 environment - not rewrite every test.

**Comment by MasterOdin** [comment]
> Well, nothing is currently testing these changes. Just need to create a single mysql 8 environment - not rewrite every test.

Added a workflow for just mysql 8. Not sure it'll run before getting merged? Not sure though.

**Comment by othercorey** [comment]
You should be able to test it on your fork.

**Comment by MasterOdin** [comment]
@othercorey https://github.com/MasterOdin/phinx/actions/runs/98798671

File: tests/Phinx/Db/Adapter/MysqlAdapterTest.php (hunk 6 above)
Comment (othercorey) [reply tests/Phinx/Db/Adapter/MysqlAdapterTest.php:712]: Typically, you would want to check for the feature you want to use/avoid not a version number.

Comment (othercorey) [reply tests/Phinx/Db/Adapter/MysqlAdapterTest.php:712]: Unit tests are ok to have special version number checks -- but then you'd simply do the version compare in the unit test.

Comment (MasterOdin) [reply tests/Phinx/Db/Adapter/MysqlAdapterTest.php:712]: Again, what are you asking for with this review? It's not clear to me.

Let's take the `testAddBooleanColumnWithSignedEqualsFalse` function.

It's currently written as:
```php
    public function testAddBooleanColumnWithSignedEqualsFalse()
    {
        $table = new \Phinx\Db\Table('table1', [], $this->adapter);
        $table->save();
        $this->assertFalse($table->hasColumn('test_boolean'));
        $table->addColumn('test_boolean', 'boolean', ['signed' => false])
              ->save();
        $rows = $this->adapter->fetchAll('SHOW COLUMNS FROM table1');

        $type = $this->usingMysql8() ? 'tinyint' : 'tinyint(1)';
        $this->assertEquals($type . ' unsigned', $rows[1]['Type']);
    }
```

I could split this into two different tests depending on version:
```php
    public function testAddBooleanColumnWithSignedEqualsFalse()
    {
        $this->adapter->connect();
        if ($this->usingMysql8()) {
            $this->markTestSkipped('Need to be using mysql < 8');
        }        
        $table = new \Phinx\Db\Table('table1', [], $this->adapter);
        $table->save();
        $this->assertFalse($table->hasColumn('test_boolean'));
        $table->addColumn('test_boolean', 'boolean', ['signed' => false])
              ->save();
        $rows = $this->adapter->fetchAll('SHOW COLUMNS FROM table1');

        $this->assertEquals('tinyint(1) unsigned', $rows[1]['Type']);
    }

    public function testAddBooleanColumnWithSignedEqualsFalseForMysql8()
    {
        $this->adapter->connect();
        if (!$this->usingMysql8()) {
            $this->markTestSkipped('Need to be using mysql 8+');
        }
        $table = new \Phinx\Db\Table('table1', [], $this->adapter);
        $table->save();
        $this->assertFalse($table->hasColumn('test_boolean'));
        $table->addColumn('test_boolean', 'boolean', ['signed' => false])
              ->save();
        $rows = $this->adapter->fetchAll('SHOW COLUMNS FROM table1');

        $this->assertEquals('tinyint unsigned', $rows[1]['Type']);
    }
```

Version check though is kind of the best way to check for a specific feature given it's just an attribute look-up on the connection that PDO readily exposes, instead of having to run 2+ throwaway queries to determine whether it exists or not.

Comment (othercorey) [reply tests/Phinx/Db/Adapter/MysqlAdapterTest.php:712]: Following the precedent in cakephp, I'm saying we wouldn't have an `isMysql8` helper directly in the driver. We would expose the version number and the unit test can perform any special version-specific hacks we want.

The driver would typically expose helpers like `supportsIntegerWidths()` -- if needed. But, since this is only for unit tests, I think exposing just the version number is good enough since we don't have features bound to that.

Comment (othercorey) [reply tests/Phinx/Db/Adapter/MysqlAdapterTest.php:712]: To be specific, I would replace the `usingMysql8()` helper with `getVersion()`.

Comment (othercorey) [reply tests/Phinx/Db/Adapter/MysqlAdapterTest.php:712]: This is good for now. I misread that it was entirely in the unit test although we might want to put the version wrapper in the adapter.
