### PR TITLE
Fix deprecation warning on Config::offsetGet function

### LINKED ISSUE #2110: Deprecation warning in PHP 8.1 with Phinx 0.13.0
<b>Deprecated</b>:  Return type of Phinx\Config\Config::offsetGet($id) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/html/elternsprechtag/vendor/robmorgan/phinx/src/Phinx/Config/Config.php</b> on line <b>510</b><br>

### PR DESCRIPTION
**Pull request by MasterOdin**
Fixes #2110 

Adds the `#[\ReturnTypeWillChange]` annotation to the `Config::offsetGet` function as to properly type it requires using the `mixed` keyword added in 8.1 and we still support 7.2+

### CODE REVIEW

File: src/Phinx/Config/Config.php [hunk 1]
```diff
@@ -533,6 +536,7 @@ public function offsetExists($id): bool
      * @param mixed $id ID
      * @return void
      */
+    #[\ReturnTypeWillChange]
     public function offsetUnset($id): void
```
Comment (othercorey) [inline src/Phinx/Config/Config.php]: I don't think this one will change.

File: src/Phinx/Config/Config.php [hunk 2]
```diff
@@ -522,6 +524,7 @@ public function offsetGet($id)
      * @param mixed $id ID
      * @return bool
      */
+    #[\ReturnTypeWillChange]
```
Comment (othercorey) [inline src/Phinx/Config/Config.php]: I don't think this one will change.

File: src/Phinx/Config/Config.php [hunk 3]
```diff
@@ -495,6 +495,7 @@ protected function parseAgnosticDsn(array $options): array
      * @param mixed $value Value
      * @return void
      */
+    #[\ReturnTypeWillChange]
     public function offsetSet($id, $value): void
```
Comment (othercorey) [inline src/Phinx/Config/Config.php]: I don't think this one will change.

Comment (MasterOdin) [reply src/Phinx/Config/Config.php]: Yeah, total brain fart on doing this, only `configGet` needs it 🤦
