### PR TITLE
Fix #1583 Incorrect removing/changing columns for SQLite

### LINKED ISSUE #1583: Incorrect removing/changing columns for SQLite
**Impact**:
Database can be corrupted

**Reproduced with** SQLite library 3.28.0 (PHP 7.1.31)

**Steps to reproduce**:
1. Create migration:
```
$tableA = 'tableA';
$tableB = 'tableB';

$this->table($tableA, ['id' => false, 'primary_key' => ['id']])
    ->addColumn('id', 'integer', ['identity' => true])
    ->addColumn('columnToRemove', 'integer')
    ->create();

$this->table($tableB, ['id' => false, 'primary_key' => ['id']])
    ->addColumn('id', 'integer', ['identity' => true])
    ->addColumn('tableA_id', 'integer')
    ->addForeignKey('tableA_id', $tableA, 'id', [
        'delete' => 'CASCADE',
        'update' => 'NO_ACTION',
    ])
    ->create();

$this->table($tableA)
    ->removeColumn('columnToRemove')
    ->save();
```
2. Run `phinx migrate -vv`

**Actual table structure**:
```
create table tableB
(
  id INTEGER not null primary key autoincrement,
  tableA_id INTEGER references tmp_tableA (id) on delete cascade
);
```

**Expected table structure**: (pay attention to the name of reference table)
```
create table tableB
(
  id INTEGER not null primary key autoincrement,
  tableA_id INTEGER references tableA (id) on delete cascade
);
```

**Additional information**:
I've found following lines in SQLite changelog:
> 2018-09-15 (3.25.0) Fix table rename feature so that it also updates references to the renamed table in triggers and views.
> 2018-12-01 (3.26.0) Added the PRAGMA legacy_alter_table command, which if enabled causes the ALTER TABLE command to behave like older version of SQLite (prior to version 3.25.0) for compatibility.

Also you can read that gist: https://gist.github.com/kpcyrd/1805a9f5c87182dfe40bf4bc2b68c54e

**Possible way to fix**:
a) Existed tableA shouldn't be renamed to tmp_tableA, instead of this need to firstly create tmp_tableA, copy all data, remove tableA and rename tmp_tableA to tableA. This must work correctly
b) Set legacy_alter_table=ON while performing "such" migrations

### PR DESCRIPTION
**Pull request by gibat**
Fix #1583

### CODE REVIEW

File: tests/Phinx/Db/Adapter/SQLiteAdapterTest.php [hunk 1]
```diff
@@ -1898,4 +1898,134 @@ public function provideTablesForTruncation()
             ['create table t(id integer primary key autoincrement)', 'T', 't'],
         ];
     }
+
+    public function testForeignKeyReferenceCorrectAfterRenameColumn()
+    {
+        $refTable = new \Phinx\Db\Table('ref_table', [], $this->adapter);
```
Comment (Jeckerson) [inline tests/Phinx/Db/Adapter/SQLiteAdapterTest.php]: Can you import class?

File: tests/Phinx/Db/Adapter/SQLiteAdapterTest.php [hunk 2]
```diff
@@ -1898,4 +1898,134 @@ public function provideTablesForTruncation()
...
+        $refTable->addColumn('columnToRename', 'string')->save();
+
+        $table = new \Phinx\Db\Table('table', [], $this->adapter);
```
Comment (Jeckerson) [inline tests/Phinx/Db/Adapter/SQLiteAdapterTest.php]: Also here. Can you import class?

File: tests/Phinx/Db/Adapter/SQLiteAdapterTest.php [hunk 3]
```diff
@@ -1898,4 +1898,134 @@ public function provideTablesForTruncation()
...
+        $table->addColumn('ref_table_id', 'integer');
```
Comment (Jeckerson) [inline tests/Phinx/Db/Adapter/SQLiteAdapterTest.php]: I suggest to move `ref_table_id` string into variable, to avoid copy-pasta and make it more DRY.

File: tests/Phinx/Db/Adapter/SQLiteAdapterTest.php [hunk 4]
```diff
@@ -1898,4 +1898,134 @@ public function provideTablesForTruncation()
...
+            if ($row['tbl_name'] == $table->getName()) {
+                $sql = $row['sql'];
+            }
+        }
+        $this->assertRegExp('/REFERENCES `ref_table` \(`id`\)/', $sql);
+    }
+
+    public function testForeignKeyReferenceCorrectAfterChangeColumn()
+    {
+        $refTable = new \Phinx\Db\Table('ref_table', [], $this->adapter);
```
Comment (Jeckerson) [inline tests/Phinx/Db/Adapter/SQLiteAdapterTest.php]: Also import here.

File: tests/Phinx/Db/Adapter/SQLiteAdapterTest.php [hunk 5]
```diff
@@ -1898,4 +1898,134 @@ public function provideTablesForTruncation()
...
+        $refTable->addColumn('columnToChange', 'string')->save();
+
+        $table = new \Phinx\Db\Table('table', [], $this->adapter);
```
Comment (Jeckerson) [inline tests/Phinx/Db/Adapter/SQLiteAdapterTest.php]: Also import here.

File: tests/Phinx/Db/Adapter/SQLiteAdapterTest.php [hunk 6]
```diff
@@ -1898,4 +1898,134 @@ public function provideTablesForTruncation()
...
+            if ($row['tbl_name'] == $table->getName()) {
+                $sql = $row['sql'];
+            }
+        }
+        $this->assertRegExp('/REFERENCES `ref_table` \(`id`\)/', $sql);
+    }
+
+    public function testForeignKeyReferenceCorrectAfterRemoveColumn()
+    {
+        $refTable = new \Phinx\Db\Table('ref_table', [], $this->adapter);
```
Comment (Jeckerson) [inline tests/Phinx/Db/Adapter/SQLiteAdapterTest.php]: Also import here.

File: tests/Phinx/Db/Adapter/SQLiteAdapterTest.php [hunk 7]
```diff
@@ -1898,4 +1898,134 @@ public function provideTablesForTruncation()
...
+        $refTable->addColumn('columnToRemove', 'string')->save();
+
+        $table = new \Phinx\Db\Table('table', [], $this->adapter);
```
Comment (Jeckerson) [inline tests/Phinx/Db/Adapter/SQLiteAdapterTest.php]: Also import here.

File: tests/Phinx/Db/Adapter/SQLiteAdapterTest.php [hunk 8]
```diff
@@ -1898,4 +1898,134 @@ public function provideTablesForTruncation()
...
+            if ($row['tbl_name'] == $table->getName()) {
+                $sql = $row['sql'];
+            }
+        }
+        $this->assertRegExp('/REFERENCES `ref_table` \(`id`\)/', $sql);
+    }
+
+    public function testForeignKeyReferenceCorrectAfterChangePrimaryKey()
+    {
+        $refTable = new \Phinx\Db\Table('ref_table', [], $this->adapter);
```
Comment (Jeckerson) [inline tests/Phinx/Db/Adapter/SQLiteAdapterTest.php]: Also import here.

File: tests/Phinx/Db/Adapter/SQLiteAdapterTest.php [hunk 9]
```diff
@@ -1898,4 +1898,134 @@ public function provideTablesForTruncation()
...
+        $refTable->addColumn('additional_id', 'integer')->save();
+
+        $table = new \Phinx\Db\Table('table', [], $this->adapter);
```
Comment (Jeckerson) [inline tests/Phinx/Db/Adapter/SQLiteAdapterTest.php]: Also import here.

File: tests/Phinx/Db/Adapter/SQLiteAdapterTest.php [hunk 10]
```diff
@@ -1898,4 +1898,134 @@ public function provideTablesForTruncation()
...
+            if ($row['tbl_name'] == $table->getName()) {
+                $sql = $row['sql'];
+            }
+        }
+        $this->assertRegExp('/REFERENCES `ref_table` \(`id`\)/', $sql);
+    }
+
+    public function testForeignKeyReferenceCorrectAfterDropForeignKey()
+    {
+        $refTableAdditional = new \Phinx\Db\Table('ref_table_additional', [], $this->adapter);
```
Comment (Jeckerson) [inline tests/Phinx/Db/Adapter/SQLiteAdapterTest.php]: Also import here.

File: tests/Phinx/Db/Adapter/SQLiteAdapterTest.php [hunk 11]
```diff
@@ -1898,4 +1898,134 @@ public function provideTablesForTruncation()
...
+        $refTableAdditional->save();
+
+        $refTable = new \Phinx\Db\Table('ref_table', [], $this->adapter);
```
Comment (Jeckerson) [inline tests/Phinx/Db/Adapter/SQLiteAdapterTest.php]: Also import here.

File: tests/Phinx/Db/Adapter/SQLiteAdapterTest.php [hunk 12]
```diff
@@ -1898,4 +1898,134 @@ public function provideTablesForTruncation()
...
+        $refTable->addColumn('ref_table_additional_id', 'integer');
+        $refTable->addForeignKey('ref_table_additional_id', 'ref_table_additional', 'id');
+        $refTable->save();
+
+        $table = new \Phinx\Db\Table('table', [], $this->adapter);
```
Comment (Jeckerson) [inline tests/Phinx/Db/Adapter/SQLiteAdapterTest.php]: Also import here.

File: tests/Phinx/Db/Adapter/SQLiteAdapterTest.php (hunk 1 above)
Comment (gibat) [reply tests/Phinx/Db/Adapter/SQLiteAdapterTest.php]: Thit test suite contains many usages of that class, so i've maked new tests similar to existed. Also there are namespace \Phinx\Db\Table and class with exact "path". I propose to leave it as is :)

Comment (dereuromark) [reply tests/Phinx/Db/Adapter/SQLiteAdapterTest.php]: Yep, this should be done using a code sniffer as automated approach instead.

File: tests/Phinx/Db/Adapter/SQLiteAdapterTest.php (hunk 5 above)
Comment (dereuromark) [reply tests/Phinx/Db/Adapter/SQLiteAdapterTest.php]: Please don't spam the thread with all instances of the same thing, a "see below for other occurances" usually suffices.

File: tests/Phinx/Db/Adapter/SQLiteAdapterTest.php [hunk 13]
```diff
@@ -1898,4 +1898,145 @@ public function provideTablesForTruncation()
...
+
+        $refTable->renameColumn($refTableColumnToRename, $refTableRenamedColumn)->save();
+
+        $this->assertTrue($this->adapter->hasForeignKey($table->getName(), [$refTableColumnId]));
+        $this->assertFalse($this->adapter->hasTable("tmp_{$refTable->getName()}"));
+        $this->assertTrue($this->adapter->hasColumn($refTable->getName(), $refTableRenamedColumn));
+
+        $rows = $this->adapter->fetchAll('select * from sqlite_master where `type` = \'table\'');
+        foreach ($rows as $row) {
+            if ($row['tbl_name'] == $table->getName()) {
```
Comment (dereuromark) [inline tests/Phinx/Db/Adapter/SQLiteAdapterTest.php]: `===` for string comparison

File: tests/Phinx/Db/Adapter/SQLiteAdapterTest.php (hunk 3 above)
Comment (gibat) [reply tests/Phinx/Db/Adapter/SQLiteAdapterTest.php]: Fixed:
- all column names used twice or more was moved to variables
- all table names now received by $table->getName()

File: tests/Phinx/Db/Adapter/SQLiteAdapterTest.php (hunk 13 above)
Comment (gibat) [reply tests/Phinx/Db/Adapter/SQLiteAdapterTest.php]: Fixed

File: src/Phinx/Db/Adapter/SQLiteAdapter.php [hunk 14]
```diff
@@ -791,17 +796,24 @@ protected function beginAlterByCopyTable($tableName)
...
-                )
+            // Table name in SQLite can be hilarious inside declaring SQL:
+            // - tableName
+            // - `tableName`
+            // - "tableName"
+            // - [this is a valid table name too!]
+            // - etc.
+            // Just remove all characters before first "(" and build them again
+            $createSQL = preg_replace(
+                "/^CREATE TABLE .* \(/Ui",
```
Comment (garas) [inline src/Phinx/Db/Adapter/SQLiteAdapter.php]:
```suggestion
                "/^CREATE TABLE [^(]+ \(/Ui",
```

- use `+` because `*` can match 0 times
- use `[^(]` to match any char except `(`

Previous expression would match `t ( id integer` as table name in `CREATE TABLE ​t ( id integer (5))`

Comment (garas) [reply src/Phinx/Db/Adapter/SQLiteAdapter.php]: Oh, ` U (PCRE_UNGREEDY)` flag modifies this behavior...
