### PR TITLE
Write CLI errors to stderr

### LINKED ISSUE #2270: (At least) Non-interactive commands should write errors to STDERR
Right now commands like `migrate` write errors to STDOUT. This is wrong. Errors, especially from commands that are commonly used non-interactively, need to be written to STDERR so that scripts executing Phinx can easily distinguish between information (STDOUT) and errors (STDERR), possibly redirecting either of them to different locations.

Here's how:
https://symfony.com/doc/current/console/style.html#writing-to-the-error-output

### PR DESCRIPTION
**Pull request by InvisibleSmiley**
Fixes #2270.

In the end I chose to copy/adapt OutputStyle::getErrorOutput as a new protected method on the abstract command rather than using SymfonyStyle because:

1. creating SymfonyStyle requires both $input and $output, but some existing methods only receive $output
2. SymfonyStyle behaves differently than the plain OutputStyle, which might introduce new issues

I also fixed the exit code for the case where no aliases exist, applying the rule "error output -> exit code 1".

### CODE REVIEW

File: src/Phinx/Console/Command/ListAliases.php [hunk 1]
```diff
@@ -68,15 +68,17 @@ function ($alias, $class) use ($maxAliasLength, $maxClassLength) {
...
 
-        return self::CODE_SUCCESS;
+        self::getErrorOutput($output)->writeln(
+            sprintf(
+                '<error>No aliases defined in %s</error>',
+                Util::relativePath($this->config->getConfigFilePath())
+            )
+        );
+
+        return self::CODE_ERROR;
```
Comment (MasterOdin) [inline src/Phinx/Console/Command/ListAliases.php]: I'm not sure not having any aliases would constitute the command failing per se, should just mean that you've not set any up. I'd leave this as always returning `self::CODE_SUCCESS`.

Comment (InvisibleSmiley) [reply src/Phinx/Console/Command/ListAliases.php]: I'd be OK with that if the message would be downgraded to a warning or info; otherwise it'll be inconsistent (and as I wrote, my goal was to achieve consistency).

Comment (MasterOdin) [reply src/Phinx/Console/Command/ListAliases.php]: Symfony does not ship with a warning style out of the box for the console, so I'm fine downgrading it to use `<info>` instead, or I guess could do similar to this:

https://github.com/cakephp/phinx/blob/efd7cf8b8fe3ed3ce0a6bb77fd079bcb5b732026/src/Phinx/Console/Command/AbstractCommand.php#L436

where we wrap a "warning" text in `<comment>` so it gives a bit of visual separation to the user.

Comment (InvisibleSmiley) [reply src/Phinx/Console/Command/ListAliases.php]: Implemented as suggested

File: src/Phinx/Db/Adapter/SQLiteAdapter.php [hunk 2]
```diff
@@ -204,7 +204,7 @@ public function connect(): void
      */
     public static function getSuffix(array $options): string
     {
-        if ($options['name'] === self::MEMORY) {
+        if (($options['name'] ?? '') === self::MEMORY) {
```
Comment (InvisibleSmiley) [inline src/Phinx/Db/Adapter/SQLiteAdapter.php:207]: This produced a notice when running tests (with `error_reporting = E_ALL` in php.ini)

File: phpcs.xml [hunk 3]
```diff
@@ -4,6 +4,12 @@
 
     <rule ref="CakePHP"/>
 
+    <rule ref="SlevomatCodingStandard.Namespaces.UnusedUses">
```
Comment (InvisibleSmiley) [inline phpcs.xml:7]: The tests do not contain all necessary imports (uses) right now because without this PHPCS will complain.
I added the missing imports to MigrateTest and will leave the rest for someone else to clean up.

**Review by MasterOdin — APPROVED** [review]

**Comment by MasterOdin** [comment]
Thanks for your PR!
