### PR TITLE
Fix :: Postgres :: Change column type from text to integer | fixed #1940

### LINKED ISSUE #1940: Postgresql cannot change column type from text to integer
Migration code:
```php
$products = $this->table('products');
$products->changeColumn('product_id', 'biginteger')
         ->save();
```

Error:
```sh
PDOException: SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "product_id" cannot be cast automatically to type bigint
HINT:  You might need to specify "USING product_id::bigint". in /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:181
Stack trace:
#0 /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(181): PDO->exec()
#1 /vendor/robmorgan/phinx/src/Phinx/Db/Util/AlterInstructions.php(112): Phinx\Db\Adapter\PdoAdapter->execute()
#2 /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(606): Phinx\Db\Util\AlterInstructions->execute()
#3 /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(981): Phinx\Db\Adapter\PdoAdapter->executeAlterSteps()
#4 /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(484): Phinx\Db\Adapter\PdoAdapter->executeActions()
#5 /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(434): Phinx\Db\Adapter\AdapterWrapper->executeActions()
#6 /vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(153): Phinx\Db\Adapter\TimedOutputAdapter->executeActions()
#7 /vendor/robmorgan/phinx/src/Phinx/Db/Table.php(722): Phinx\Db\Plan\Plan->execute()
#8 /vendor/robmorgan/phinx/src/Phinx/Db/Table.php(629): Phinx\Db\Table->executeActions()
#9 /vendor/robmorgan/phinx/src/Phinx/Db/Table.php(688): Phinx\Db\Table->update()
#10 /db/migrations/20201208150956_update_products_columns.php(15): Phinx\Db\Table->save()
#11 /vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(109): UpdateProductsColumns->up()
#12 /vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(383): Phinx\Migration\Manager\Environment->executeMigration()
#13 /vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(356): Phinx\Migration\Manager->executeMigration()
#14 /vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(123): Phinx\Migration\Manager->migrate()
#15 /vendor/symfony/console/Command/Command.php(255): Phinx\Console\Command\Migrate->execute()
#16 /vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run()
#17 /vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#18 /vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(69): Symfony\Component\Console\Application->doRun()
#19 /vendor/symfony/console/Application.php(166): Phinx\Console\PhinxApplication->doRun()
#20 /vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#21 {main}
```

This is because it is not easy to change the field type if the table contains data. Since the varchar type was used, PostgreSQL can't determine if the value belongs to integer.

The problem can be solved by using USING - the expression specified in the error message. So we will perform data conversion to integer correctly:
```sql
ALTER TABLE products ALTER COLUMN product_id TYPE bigint USING (product_id::bigint);
```

### PR DESCRIPTION
**Pull request by qWici**
Since bigint has the largest range of numbers I used it to convert a value to a number and no need to worry about smaller numbers. I also added 3 different tests for different types of integers. I'm not sure if this is the right thing to do now, but there may be some changes with the types in the future.

### CODE REVIEW

File: src/Phinx/Db/Adapter/PostgresAdapter.php [hunk 1]
```diff
@@ -546,6 +546,14 @@ protected function getChangeColumnInstructions($tableName, $columnName, Column $
             $this->quoteColumnName($columnName),
             $this->getColumnSqlDefinition($newColumn)
         );
+
+        if (in_array($newColumn->getType(), ['smallinteger', 'integer', 'biginteger'])) {
```
Comment (dereuromark) [inline src/Phinx/Db/Adapter/PostgresAdapter.php:550]: can we set 3rd arg to true?

File: tests/Phinx/Db/Adapter/PostgresAdapterTest.php [hunk 2]
```diff
@@ -833,6 +833,51 @@ public function testChangeColumn()
         $this->assertTrue($this->adapter->hasColumn('t', 'column2'));
     }
 
+    public function testChangeColumnFromTextToSmallInteger()
```
Comment (MasterOdin) [inline tests/Phinx/Db/Adapter/PostgresAdapterTest.php:836]: You can condense each of these different tests into a singular one using a [Data Provider](https://phpunit.readthedocs.io/en/9.3/writing-tests-for-phpunit.html#data-providers). There are examples of usage in other places in this file.

The data provider for this can return something like:
```
return [
  ['smallinteger', 32767],
  ['integer', 2147483647],
  ['biginteger', 9223372036854775807],
];
```

and then within the test, on the insert line, do `(string)$testValue` to get that string representation of the value.

File: tests/Phinx/Db/Adapter/PostgresAdapterTest.php [hunk 3]
```diff
@@ -833,6 +833,51 @@ public function testChangeColumn()
...
+    {
+        $table = new \Phinx\Db\Table('t', [], $this->adapter);
+        $table->addColumn('column1', 'text')
+            ->insert(['column1' => '32767'])
+            ->save();
+
+        $table->changeColumn('column1', 'smallinteger')->save();
+        $columnType = $table->getColumn('column1')->getType();
+        $this->assertTrue($columnType === 'smallinteger');
```
Comment (MasterOdin) [inline tests/Phinx/Db/Adapter/PostgresAdapterTest.php:845]:
```suggestion
        $this->assertSame($columnType, 'smallinteger');
```

File: tests/Phinx/Db/Adapter/PostgresAdapterTest.php [hunk 4]
```diff
@@ -833,6 +833,51 @@ public function testChangeColumn()
...
+
+        $row = $this->adapter->fetchRow('SELECT * FROM t');
+        $this->assertEquals(32767, $row['column1']);
```
Comment (MasterOdin) [inline tests/Phinx/Db/Adapter/PostgresAdapterTest.php:848]:
```suggestion
        $this->assertSame(32767, $row['column1']);
```

**Review by MasterOdin — CHANGES_REQUESTED** [review]

File: tests/Phinx/Db/Adapter/PostgresAdapterTest.php (hunk 4 above)
Comment (dereuromark) [reply tests/Phinx/Db/Adapter/PostgresAdapterTest.php:848]: This might not work in all DBs, as some return this as string I think.

**Review by MasterOdin — APPROVED** [review]
@dereuromark looks good to me
